/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package telas;

/**
 *
 * @author macaurycarvalho
 */
public class Atencao extends javax.swing.JPanel {

    /**
     * Creates new form Atencao
     */
    public Atencao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel7 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(96, 164, 178));
        jPanel1.setMinimumSize(new java.awt.Dimension(213, 100));
        jPanel1.setLayout(new java.awt.GridLayout());
        jPanel1.add(filler1);

        jLabel7.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grande/Group 47.png"))); // NOI18N
        jLabel7.setText("Atenção");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIconTextGap(20);
        jLabel7.setPreferredSize(new java.awt.Dimension(220, 100));
        jPanel1.add(jLabel7);

        filler2.setBackground(new java.awt.Color(96, 164, 178));
        jPanel1.add(filler2);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grande/Group 49.png"))); // NOI18N
        jLabel1.setText("Inserir Dados");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setIconTextGap(25);
        jPanel2.add(jLabel1);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grande/bloco variavel.png"))); // NOI18N
        jLabel5.setText("Variável");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setIconTextGap(25);
        jPanel2.add(jLabel5);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grande/Group 48.png"))); // NOI18N
        jLabel4.setText("Estrutura For");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setIconTextGap(25);
        jPanel2.add(jLabel4);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grande/bloco if.png"))); // NOI18N
        jLabel3.setText("Estrutura IF");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setIconTextGap(25);
        jPanel2.add(jLabel3);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grande/bloco while.png"))); // NOI18N
        jLabel6.setText("Estrutura While");
        jLabel6.setAlignmentX(0.5F);
        jLabel6.setIconTextGap(25);
        jPanel2.add(jLabel6);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grande/bloco array.png"))); // NOI18N
        jLabel2.setText("Array ou vetor");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setIconTextGap(25);
        jPanel2.add(jLabel2);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
