/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author GABRIEL
 */
public class CondicaoJP extends Elemento {

    /**
     * Creates new form CondicaoJP
     */
    public CondicaoJP() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agrupar = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jLabel1 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        AgruparCondicaoJP = new javax.swing.JPanel();
        Valor1JTF = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        CompararJCB = new javax.swing.JComboBox<>();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        Valor2JTF = new javax.swing.JTextField();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setPreferredSize(new java.awt.Dimension(300, 50));
        setLayout(new java.awt.BorderLayout());

        Agrupar.setBackground(getBackground());
        Agrupar.setLayout(new javax.swing.BoxLayout(Agrupar, javax.swing.BoxLayout.LINE_AXIS));
        Agrupar.add(filler7);

        jLabel1.setText("IF");
        Agrupar.add(jLabel1);
        Agrupar.add(filler6);

        AgruparCondicaoJP.setBackground(getBackground());
        AgruparCondicaoJP.setLayout(new javax.swing.BoxLayout(AgruparCondicaoJP, javax.swing.BoxLayout.LINE_AXIS));

        Valor1JTF.setEditable(false);
        Valor1JTF.setBorder(null);
        AgruparCondicaoJP.add(Valor1JTF);
        AgruparCondicaoJP.add(filler8);

        CompararJCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==", "!=", ">=", "<=", ">", "<" }));
        CompararJCB.setBorder(null);
        AgruparCondicaoJP.add(CompararJCB);
        AgruparCondicaoJP.add(filler10);

        Valor2JTF.setEditable(false);
        Valor2JTF.setBorder(null);
        AgruparCondicaoJP.add(Valor2JTF);
        AgruparCondicaoJP.add(filler9);

        Agrupar.add(AgruparCondicaoJP);

        add(Agrupar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agrupar;
    private javax.swing.JPanel AgruparCondicaoJP;
    private javax.swing.JComboBox<String> CompararJCB;
    private javax.swing.JTextField Valor1JTF;
    private javax.swing.JTextField Valor2JTF;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
