/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author GABRIEL
 */
public class CondicaoJP extends Elemento {

    /**
     * Creates new form CondicaoJP
     */
    public CondicaoJP() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agrupar = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(0, 0));
        jLabel1 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(0, 0));
        AgruparCondicaoJP = new javax.swing.JPanel();
        Valor1JTF = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(0, 0));
        CompararJCB = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(0, 0));
        Valor2JTF = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(0, 0));

        setLayout(new java.awt.BorderLayout());

        Agrupar.setLayout(new javax.swing.BoxLayout(Agrupar, javax.swing.BoxLayout.LINE_AXIS));
        Agrupar.add(filler5);

        jLabel1.setText("IF");
        Agrupar.add(jLabel1);
        Agrupar.add(filler4);

        AgruparCondicaoJP.setLayout(new javax.swing.BoxLayout(AgruparCondicaoJP, javax.swing.BoxLayout.LINE_AXIS));
        AgruparCondicaoJP.add(Valor1JTF);
        AgruparCondicaoJP.add(filler3);

        CompararJCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==", "!=", ">=", "<=", ">", "<" }));
        AgruparCondicaoJP.add(CompararJCB);
        AgruparCondicaoJP.add(filler1);
        AgruparCondicaoJP.add(Valor2JTF);
        AgruparCondicaoJP.add(filler2);

        Agrupar.add(AgruparCondicaoJP);

        add(Agrupar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agrupar;
    private javax.swing.JPanel AgruparCondicaoJP;
    private javax.swing.JComboBox<String> CompararJCB;
    private javax.swing.JTextField Valor1JTF;
    private javax.swing.JTextField Valor2JTF;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
