/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.awt.Color;
import java.awt.Point;
import java.awt.color.ColorSpace;
import javax.swing.JLayeredPane;
import javax.swing.border.TitledBorder;
import telas.Principal;

/**
 *
 * @author GABRIEL
 */
public class Elemento extends javax.swing.JPanel {
    private Point mouseInitPosClick;
    //private Color background;
    
    
    public Elemento() {
        initComponents();
        
        //background = getBackground();
        mouseInitPosClick = new Point();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sobrepor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sobrepor(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MousePosToMove(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
  
/*
    public Color getBackgroundColor(){
        return background;
    }
*/
    private void mover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mover
        this.setLocation((int)(evt.getX() + this.getX() - mouseInitPosClick.getX()),(int)(evt.getY() + this.getY() - mouseInitPosClick.getY()));
    }//GEN-LAST:event_mover

    private void MousePosToMove(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MousePosToMove
        mouseInitPosClick = evt.getPoint();
    }//GEN-LAST:event_MousePosToMove

    private void sobrepor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobrepor
        /*JLayeredPane camada = (JLayeredPane) this.getParent();
        
        if(JLayeredPane.getLayer(this) == JLayeredPane.DRAG_LAYER){
            camada.setLayer(this, JLayeredPane.PALETTE_LAYER);
        }else{
            camada.setLayer(this, JLayeredPane.DRAG_LAYER);
        }*/
        
    }//GEN-LAST:event_sobrepor


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
